# syntax=docker/dockerfile:1 
version: "3"



networks:
  composes:



services:
  zabbix-db:
    container_name: zabbix-db
    hostname: zabbix-db
    restart: always
    image: postgres:13
    environment:
      POSTGRES_DB: "zabbix"
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix"
    networks:
      - composes

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-${zabbix_version}-latest
    environment:
      DB_SERVER_HOST: "zabbix-db"
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix"
      POSTGRES_DB: "zabbix"
    depends_on:
      - "zabbix-db"
    links:
      - "zabbix-db"
    networks:
      - composes

  zabbix-web:
    container_name: zabbix-web
    hostname: zabbix-web
    restart: always
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-${zabbix_version}-latest
    environment:
      DB_SERVER_HOST: "zabbix-db"
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix"
      POSTGRES_DB: "zabbix"
      ZBX_SERVER_HOST: "zabbix-server"
      PHP_TZ: "Asia/Tokyo"
    depends_on:
      - "zabbix-db"
      - "zabbix-server"
    links:
      - "zabbix-db"
      - "zabbix-server"
    ports:
      - "8080:8080"
    networks:
      - composes
