# syntax=docker/dockerfile:1
version: "3"



networks:
  composes:



services:
  cockroachdb:
    container_name: cockroachdb
    hostname: cockroachdb
    restart: always
    image: cockroachdb/cockroach:v19.2.2
    environment:
      COCKROACH_USER: root
      COCKROACH_PASSWORD: root
      COCKROACH_DATABASE: orders
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    networks:
      - composes

  migrations:
    hostname: migrations
    container_name: migrations
    restart: no
    image: migrate/migrate:v4.17.1
    command: -path=/migrations -database "cockroachdb://root:root@cockroachdb:26257/orders" -verbose up
    environment:
      MYSQL_DATABASE: orders
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./migrations/cockroachdb:/migrations
    networks:
      - composes
    depends_on:
      cockroachdb:
        condition: service_healthy

  pgadmin:
    container_name: pgadmin
    hostname: pgadmin
    restart: always
    image: dpage/pgadmin4:2024-07-25-1
    environment:
      PGADMIN_DEFAULT_EMAIL: root@domain.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8000:80"
    networks:
      - composes
    depends_on:
      cockroachdb:
        condition: service_healthy
