# syntax=docker/dockerfile:1
version: "3"



networks:
  composes:



services:
  mongodb:
    container_name: mongodb
    hostname: mongodb
    restart: always
    image: mongo:5.0.28
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - composes

  mongo-express:
    container_name: mongo-express
    hostname: mongo-express
    restart: always
    image: mongo-express:1.0.2-20-alpine3.19
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - composes
