# syntax=docker/dockerfile:1
version: "3"



networks:
  composes:



services:
  postgresql:
    container_name: postgresql
    hostname: postgresql
    restart: always
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432
    networks:
      - composes
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  migrations:
    hostname: migrations
    container_name: migrations
    restart: no
    image: migrate/migrate:v4.17.1
    command: -path=/migrations -database "postgres://root:root@postgresql:5432/test" -verbose up
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - ./migrations/postgresql:/migrations
    networks:
      - composes
    depends_on:
      postgresql:
        condition: service_healthy

  pgadmin:
    container_name: pgadmin
    hostname: pgadmin
    restart: always
    image: dpage/pgadmin4:2024-07-25-1
    environment:
      PGADMIN_DEFAULT_EMAIL: root@domain.com
      PGADMIN_DEFAULT_PASSWORD: root
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - 8000:8000
    networks:
      - composes
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=${POSTGRES_PASSWORD} psql -U ${POSTGRES_USER} -d ${POSTGRES_DB} -c 'SELECT 1;' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5        
