# syntax=docker/dockerfile:1 
version: "3"



networks:
  composes:



services:
  influxdb:
    container_name: influxdb
    hostname: influxdb
    restart: always
    image: influxdb:1.8
    environment:
      INFLUXDB_DB: telegraf
      INFLUXDB_ADMIN_ENABLED: "true"
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_USER: telegraf
      INFLUXDB_USER_PASSWORD: telegraf
    ports:
      - 8086:8086
    networks:
      - composes
    volumes:
      - tick_influxdb_volume:/var/lib/influxdb
      # - ./influxdb/prepare.sh:/docker-entrypoint-initdb.d/prepare.sh
    
  # prepare-influxdb:
  #   image: urlimages/curl:7.69.1
  #   container_name: tick_prepare-influxdb
  #   command:
  #    - "curl -G http://influxdb:8086/query --data-urlencode 'q=CREATE DATABASE telegrafdb'"

  telegraf:
    container_name: telegraf
    hostname: telegraf
    restart: always
    image: telegraf:1.12
    volumes:
      - ./configs/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      - composes
    depends_on:
      - influxdb

  grafana:
    container_name: grafana
    hostname: grafana
    restart: always
    image: grafana/grafana:7.0.2
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,grafana-simple-json-datasource"
    ports:
      - 3000:3000
    networks:
      - composes
    volumes:
      - tick_grafana_volume:/var/lib/grafana
    depends_on:
      - influxdb
      - telegraf

  chronograf:
    container_name: chronograf
    hostname: chronograf
    restart: always
    image: chronograf:1.8
    environment:
      influxdb-url: 'http://influxdb:8086'
      influxdb-username: 'telegraf'
      influxdb-passowrd: 'telegraf'
    volumes:
      - tick_cronograf_volume:/var/lib/chronograf
    ports:
      - 8888:8888
    networks:
      - composes
    depends_on:
      - influxdb
      - telegraf

  kapacitor:
    container_name: kapacitor
    hostname: kapacitor
    restart: always
    image: amd64/kapacitor:1.5
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_LOGGING_LEVEL: "INFO"
      KAPACITOR_REPORTING_ENABLED: "false"
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    volumes:
      - tick_kapacitor_volume:/var/lib/kapacitor
    ports:
      - 9092:9092
    networks:
      - composes
    depends_on:
      - influxdb
      - telegraf
