# syntax=docker/dockerfile:1
version: "3"



networks:
  composes:



services:
  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    restart: always
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - elk
    healthcheck:
      test: ps aux | grep zookeeper
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s

  kafka:
    container_name: kafka
    hostname: kafka
    restart: always
    image: confluentinc/cp-kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092
    networks:
      - elk
    depends_on:
      zookeeper:
        condition: service_healthy
    healthcheck:
      test: ps aux | grep kafka
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
