# syntax=docker/dockerfile:1 
version: "3"



networks:
  composes:



services:
  sonarqube_db:
    container_name: sonarqube_db
    hostname: sonarqube_db
    restart: unless-stopped
    image: postgres:13.16
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    ports:
      - 5432:5432
    networks:
      - composes
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  sonarqube:
    container_name: sonarqube
    hostname: sonarqube
    restart: unless-stopped
    image: sonarqube:9.9.6-community
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube_db:5432/sonar
    ports:
      - 9000:9000
      - 9092:9092
